"""An app's reference, in Markdown, generated from what it declares: its
settings from its profile, its commands, keys and help from its hello. What
the panel's line searches is what the reference says, so nothing is
documented twice. `hill-ops docs [APP]` prints it.
"""

from __future__ import annotations

from settings_panel import Group, JsonStore, Setting

from .index import AppDocs, remembered
from .keytree import opener, sequences
from .panel import STRIP_HELP, hill_groups, setting_id, value_word
from .paths import config_home
from .profiles import ProfileError, load, profiles_dir

HILL_COMMANDS = [
    ["set", "SETTING VALUE", "change a setting: SETTING is its `:set` name, VALUE one of its choices"],
    ["toggle", "SETTING", "change a setting to its next value, round to the first"],
]
"""hill-ops's own commands, on every app's line, as the reference lists them."""


class Unknown(Exception):
    """An app hill-ops knows nothing of: no profile linked, no hello kept."""


def reference(app: str = "hill") -> tuple[str, list[str]]:
    """`app`'s reference, and what in it is undocumented: a setting with no
    help, a command that doesn't say what it does, a key with no label."""
    if app == "hill":
        return document("hill", hill_groups(JsonStore(config_home() / "settings.json")), AppDocs("hill", commands=HILL_COMMANDS, help=[["Strip", [list(k) for k in STRIP_HELP]]]))
    try:
        profile = load(profiles_dir() / f"{app}.toml")
    except FileNotFoundError:
        profile = None
    except (ProfileError, OSError) as e:
        raise Unknown(f"{app}'s profile can't be read: {e}") from e
    docs = next((d for d in remembered() if d.app == app), None)
    if profile is None and docs is None:
        raise Unknown(f"hill-ops doesn't know {app}: it has never said hello")
    themes = {id(profile.theme[1])} if profile and profile.theme else set()
    return document(app, profile.groups if profile else [], docs, themes)


def document(app: str, groups: list[Group], docs: AppDocs | None, themes: set[int] = frozenset()) -> tuple[str, list[str]]:
    """The reference of `app`, from its `groups` of settings and what it
    said in hello (`docs`, None if it never did). Settings whose id is in
    `themes` take Textual's themes, whatever the app has."""
    out = [f"# {app} reference", "", f"Generated by `hill-ops docs {app}` from what {app} declares; don't edit it here."]
    gaps = []
    if groups:
        out += ["", "## Settings", "", "Each with its `:set` name, what it does, its choices and its default."]
    for group in groups:
        out += ["", f"### {group.name}", "", f"{group.where}.", ""]
        for setting in group.settings:
            out.append(f"- **{setting.label}** (`{setting_id(group, setting)}`): {_sentence(setting.help)}{_choices(setting, id(setting) in themes)}")
            if not setting.help.strip():
                gaps.append(f"setting {setting_id(group, setting)} has no help")
    if docs is None:
        out += ["", f"{app} hasn't said hello to hill-ops yet, so its commands and keys aren't known."]
        return "\n".join(out) + "\n", gaps
    commands = [c for c in docs.commands if c and isinstance(c[0], str)]
    keys = sequences(docs.tree, opener(docs.keys))
    if commands:
        out += ["", "## Commands", "", "Typed after `:` on the panel's line"
                + (", or reached by the keys after them in the key tree." if keys else "."), ""]
    for command in commands:
        args, what = (str(c or "") for c in (list(command) + ["", ""])[1:3])
        choices = command[3] if len(command) > 3 and isinstance(command[3], list) else []
        more = f" Choices: {', '.join(f'`{c}`' for c in choices)}." if choices else ""
        tree = f" (`{keys[command[0]]}`)" if command[0] in keys else ""
        out.append(f"- `:{command[0]}{' ' + args if args else ''}`{tree}: {_sentence(what)}{more}")
        if not what.strip():
            gaps.append(f"command :{command[0]} doesn't say what it does")
    strip = [k for k in docs.keys if len(k) > 1]
    sections = [s for s in docs.help if len(s) > 1 and isinstance(s[0], str) and isinstance(s[1], list)]
    if strip or sections:
        out += ["", "## Keys"]
    for title, keys in ([("Strip", strip)] if strip else []) + [(s[0], [k for k in s[1] if isinstance(k, list) and k]) for s in sections]:
        out += ["", f"### {title}", ""]
        for key in keys:
            label = str(key[1]) if len(key) > 1 else ""
            out.append(f"- `{key[0]}`: {label}")
            if not label.strip():
                gaps.append(f"key {key[0]} in {title} has no label")
    return "\n".join(out) + "\n", gaps


def _sentence(text: str) -> str:
    text = text.strip()
    return text if not text or text.endswith((".", "?", "!")) else f"{text}."


def _choices(setting: Setting, themes: bool) -> str:
    if themes:
        return f" Choices: Textual's themes. Default: `{value_word(setting.default)}`."
    shown = [f"`{value_word(o)}`" + (f" ({setting.show(o)})" if setting.show(o) != value_word(o) else "") for o in setting.options()]
    return f" Choices: {', '.join(shown)}. Default: `{value_word(setting.default)}`."
